---
name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Set Python exection path for pytest
    - name: Run tests
      run: |
        PYTHONPATH=. pytest

    - name: Train model
      run: |
        python train.py

    - name: Deploy model
      run: |
        echo "Deploying model..."
        # Simulate deployment step
        if [ -f "model.joblib" ]; then echo "Model deployed successfully"; else echo "Model deployment failed"; exit 1; fi
  
  deploy_to_s3:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS credentials from AWS account
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    # There isn't an offical aws-actions for deploy/synching with S3. Use unofficial or workaround  
    - name: Install AWS CLI
      run: |
        pip install awscli

    - name: Download model artifact
      uses: actions/download-artifact@v2
      with:
        name: model.joblib
    
    - name: Deploy model to S3
      run: |
        aws s3 cp model.joblib s3://nabeel-cicd-mi-model/model/model.joblib
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: us-east-1
